### ISSUE TITLE
在TensorFlow1.0下使用出现错误

### ISSUE THREAD

**Issue by BillPei** [zhangzibin/PairCNN-Ranking#3]
我在使用您的代码的时候出现如下错误，请问您该如何解决

InvalidArgumentError (see above for traceback): Matrix size-incompatible: In[0]: [64,128], In[1]: [128,128]
	 [[Node: similarity/MatMul = MatMul[T=DT_FLOAT, transpose_a=true, transpose_b=false, _device="/job:localhost/replica:0/task:0/cpu:0"](h_pool_left, W/read)]]

**Comment by zhangzibin** [comment]
@BillPei 应该是一些API的参数变了，提供一下traceback？
